# Generated by Django 4.0.6 on 2022-08-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_action_text_alter_todo_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='assignee_name',
            new_name='resource_name',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='assignee_pic_url',
            new_name='resource_pic_url',
        ),
    ]
