# Generated by Django 4.0.6 on 2022-08-08 09:43

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=80)),
                ('course_name', models.CharField(max_length=80)),
                ('grade', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('website', models.URLField()),
                ('linkdin', models.URLField()),
                ('fb', models.URLField()),
                ('insta', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('gender', models.CharField(max_length=20)),
                ('admin_type', models.CharField(choices=[('client', 'CLIENT'), ('program', 'PROGRAM'), ('super', 'SUPER')], default=core.utils.AdminType['CLIENT'], max_length=50)),
                ('education', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.education')),
                ('interest', models.ManyToManyField(to='user_profile.interests')),
                ('social_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.sociallinks')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.workexperience')),
            ],
        ),
    ]
