# Generated by Django 4.0.6 on 2022-08-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
