# Generated by Django 4.0.6 on 2022-08-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_profile_admin_type_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(null=True, to='user_profile.interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.sociallinks'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.workexperience'),
        ),
    ]
